"""initial_schema

Revision ID: 3de79b987bc8
Revises: 
Create Date: 2026-06-17 16:37:28.771853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3de79b987bc8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('discord_city_role_id', sa.String(length=25), nullable=True),
    sa.Column('discord_contributor_role_id', sa.String(length=25), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forks_slug'), 'forks', ['slug'], unique=True)
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_slug'), 'groups', ['slug'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plugin_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_key'), 'permissions', ['key'], unique=True)
    op.create_table('plugin_registry',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('members_synced', sa.Integer(), nullable=False),
    sa.Column('members_added', sa.Integer(), nullable=False),
    sa.Column('members_removed', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('discord_member_count', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('plugin_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_table('delegations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delegator_id', sa.UUID(), nullable=False),
    sa.Column('delegatee_id', sa.UUID(), nullable=False),
    sa.Column('permission_key', sa.String(length=150), nullable=False),
    sa.Column('delegation_ref', sa.Text(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delegatee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delegator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_key'], ['permissions.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegations_delegatee_id'), 'delegations', ['delegatee_id'], unique=False)
    op.create_index(op.f('ix_delegations_delegator_id'), 'delegations', ['delegator_id'], unique=False)
    op.create_table('discord_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('discord_id', sa.String(length=25), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('discriminator', sa.String(length=4), nullable=True),
    sa.Column('global_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_hash', sa.String(length=100), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_discord_accounts_discord_id'), 'discord_accounts', ['discord_id'], unique=True)
    op.create_table('discord_role_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('discord_role_id', sa.String(length=25), nullable=False),
    sa.Column('discord_role_name', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_role_mappings_discord_role_id'), 'discord_role_mappings', ['discord_role_id'], unique=True)
    op.create_index(op.f('ix_discord_role_mappings_group_id'), 'discord_role_mappings', ['group_id'], unique=False)
    op.create_table('fork_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fork_id', sa.UUID(), nullable=False),
    sa.Column('track', sa.String(length=50), nullable=True),
    sa.Column('local_role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fork_id'], ['forks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fork_id', name='uq_fork_member_user_fork')
    )
    op.create_index(op.f('ix_fork_members_fork_id'), 'fork_members', ['fork_id'], unique=False)
    op.create_index(op.f('ix_fork_members_user_id'), 'fork_members', ['user_id'], unique=False)
    op.create_table('grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_type', sa.String(length=20), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('permission_key', sa.String(length=150), nullable=False),
    sa.Column('resource_scope', sa.String(length=255), nullable=True),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['permission_key'], ['permissions.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grants_permission_key'), 'grants', ['permission_key'], unique=False)
    op.create_index('ix_grants_principal', 'grants', ['principal_type', 'principal_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_membership_user_group')
    )
    op.create_index(op.f('ix_memberships_group_id'), 'memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_group_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('ix_grants_principal', table_name='grants')
    op.drop_index(op.f('ix_grants_permission_key'), table_name='grants')
    op.drop_table('grants')
    op.drop_index(op.f('ix_fork_members_user_id'), table_name='fork_members')
    op.drop_index(op.f('ix_fork_members_fork_id'), table_name='fork_members')
    op.drop_table('fork_members')
    op.drop_index(op.f('ix_discord_role_mappings_group_id'), table_name='discord_role_mappings')
    op.drop_index(op.f('ix_discord_role_mappings_discord_role_id'), table_name='discord_role_mappings')
    op.drop_table('discord_role_mappings')
    op.drop_index(op.f('ix_discord_accounts_discord_id'), table_name='discord_accounts')
    op.drop_table('discord_accounts')
    op.drop_index(op.f('ix_delegations_delegator_id'), table_name='delegations')
    op.drop_index(op.f('ix_delegations_delegatee_id'), table_name='delegations')
    op.drop_table('delegations')
    op.drop_index('ix_audit_log_created_at', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('sync_runs')
    op.drop_table('plugin_registry')
    op.drop_index(op.f('ix_permissions_key'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_groups_slug'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_forks_slug'), table_name='forks')
    op.drop_table('forks')
    # ### end Alembic commands ###
